name: tnp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_rating_stars: ^1.0.3+4
  auto_size_text: ^3.0.0

  #structs
  get: ^4.3.0

  #Screens
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.9.2
  flutter_custom_clippers: ^2.0.0
  hexcolor: ^2.0.5
  device_preview: ^0.7.5
  font_awesome_flutter: ^9.2.0
  share: ^2.0.4
  url_launcher: ^6.0.13
  social_share: ^2.1.1
  share_plus: ^3.0.4
  flutter_open_whatsapp: ^0.1.2
  geocode: ^1.0.1
  location: ^4.2.0
  geocoder: ^0.2.1
  screenshot: ^1.2.3
  estados_municipios: ^2.0.0+1
  local_auth: ^1.1.8
  social_share_plugin: ^0.3.1+1
  #Text and Output
  flutter_masked_text: ^0.8.0
  dropdown_plus: ^0.0.9
  brasil_fields: ^1.2.0
  pin_code_fields: ^7.3.0
  flutter_credit_card: ^3.0.1
  geocoding: ^2.0.1
  currency_text_input_formatter: ^2.1.5
  #DataBase
  sqflite: ^2.0.0+4
  path_provider: ^2.0.5
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  dropdown_search: ^2.0.0
  quiver: ^3.0.1+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/bg.png 
   - assets/logo.png
   - assets/quotas.png
   - assets/quotas-branco.png
   - assets/twitter.png
   - assets/whatsapp.png
   - assets/facebook.png
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher.png"
  image_path_android: "assets/launcher.png"